Ascent/Areas/Survey/Controllers/OutcomeSurveyController.cs
using System.ComponentModel.DataAnnotations;
using Ascent.Helpers;
using Ascent.Models;
using Ascent.Security;
using Ascent.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ascent.Areas.Survey.Controllers
{
    [Area("Survey")]
    [Authorize(Policy = Constants.Policy.CanWrite)]
    public class OutcomeSurveyController : Controller
    {
        private readonly SurveyService _surveyService;
        private readonly ProgramService _programService;
        private readonly SurveyDataService _surveyDataService;

        private readonly AppMapper _mapper;
        private readonly ILogger<OutcomeSurveyController> _logger;

        public OutcomeSurveyController(SurveyService surveyService, ProgramService programService, SurveyDataService surveyDataService,
            AppMapper mapper, ILogger<OutcomeSurveyController> logger)
        {
            _surveyService = surveyService;
            _programService = programService;
            _surveyDataService = surveyDataService;
            _mapper = mapper;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var surveys = _surveyService.GetSurveys();
            var outcomeSurveys = _surveyService.GetOutcomeSurveys();
            var outcomeSurveyIds = _surveyService.GetOutcomeSurveys().Select(s => s.SurveyId).ToHashSet();

            ViewBag.ShowAdd = surveys.Where(s => !outcomeSurveyIds.Contains(s.Id) && s.Name.Contains("Outcome")).Count() > 0;

            return View(outcomeSurveys);
        }

        public IActionResult View(int id)
        {
            var outcomeSurvey = _surveyService.GetOutcomeSurveyWithProgram(id);

            ViewBag.Questions = _surveyService.GetQuestions(outcomeSurvey.SurveyId);

            return View(outcomeSurvey);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var surveys = _surveyService.GetSurveys();
            var outcomeSurveyIds = _surveyService.GetOutcomeSurveys().Select(s => s.SurveyId).ToHashSet();

            ViewBag.Programs = _programService.GetPrograms();
            ViewBag.Surveys = surveys.Where(s => !outcomeSurveyIds.Contains(s.Id) && s.Name.Contains("Outcome")).ToList();

            return View(new OutcomeSurveyInputModel());
        }

        [HttpPost]
        public IActionResult Add(OutcomeSurveyInputModel input)
        {
            var outcomeSurvey = _mapper.Map(input);

            var program = _programService.GetProgram(input.ProgramId);
            outcomeSurvey.QuestionIds = new int[program.Outcomes.Count];

            var questions = _surveyService.GetQuestions(input.SurveyId);
            for (int i = 0; i < outcomeSurvey.QuestionIds.Length; ++i)
                outcomeSurvey.QuestionIds[i] = questions[i].Id;

            _surveyService.AddOutcomeSurvey(outcomeSurvey);
            _logger.LogInformation("{user} created outcome survey {survey}", User.GetName(), outcomeSurvey.Id);

            return RedirectToAction("View", new { id = outcomeSurvey.Id });
        }

        public IActionResult ImportData(int id)
        {
            var outcomeSurvey = _surveyService.GetOutcomeSurvey(id);
            if (outcomeSurvey == null) return NotFound();

            _surveyDataService.DeleteData(outcomeSurvey);

            var program = _programService.GetProgram(outcomeSurvey.ProgramId);
            var responses = _surveyService.GetResponses(outcomeSurvey.SurveyId);
            var questions = _surveyService.GetQuestions(outcomeSurvey.SurveyId).ToDictionary(q => q.Id, q => q);
            var questionIdToOutcomeIndex = outcomeSurvey.QuestionIds.Select((id, index) => new { id, index })
                .ToDictionary(x => x.id, x => x.index);

            foreach (var response in responses)
            {
                foreach (var answer in response.Answers)
                {
                    if (questionIdToOutcomeIndex.ContainsKey(answer.QuestionId))
                    {
                        var surveyDataPoint = new SurveyDataPoint
                        {
                            ConstituencyType = outcomeSurvey.ConstituencyType,
                            Year = new Term((DateTime)(response.TimeSubmitted?.ToLocalTime())).Year,
                            ProgramId = outcomeSurvey.ProgramId,
                            OutcomeId = program.Outcomes[questionIdToOutcomeIndex[answer.QuestionId]].Id,
                            SurveyId = outcomeSurvey.SurveyId,
                            AnswerId = answer.Id
                        };

                        var question = questions[answer.QuestionId];
                        if (question.Type == QuestionType.Choice && question.MinSelection == 1 && question.MaxSelection == 1)
                        {
                            for (int i = 0; i < question.Choices.Count; ++i)
                                if (question.Choices[i] == answer.SingleSelection)
                                {
                                    surveyDataPoint.Value = i + 1;
                                    break;
                                }
                        }
                        else if (question.Type == QuestionType.Rating)
                        {
                            surveyDataPoint.Value = (int)answer.Rating;
                        }
                        else
                        {
                            _logger.LogWarning("Invalid question type {type} of question {question}", question.Type, question.Id);
                            continue;
                        }

                        _surveyDataService.AddData(surveyDataPoint);
                    }
                }
            }

            outcomeSurvey.DataImportTime = DateTime.UtcNow;
            _surveyDataService.SaveChanges();
            _logger.LogInformation("{user} imported data from outcome survey {survey}", User.GetName(), outcomeSurvey.Id);

            return RedirectToAction("Index");
        }
    }
}

namespace Ascent.Models
{
    public class OutcomeSurveyInputModel
    {
        [Display(Name = "Constituency Type")]
        public ConstituencyType ConstituencyType { get; set; }

        [Display(Name = "Survey")]
        public int SurveyId { get; set; }

        [Display(Name = "Program")]
        public int ProgramId { get; set; }

        public int[] QuestionIds { get; set; }
    }
}

Ascent/Areas/Survey/Views/OutcomeSurvey/Add.cshtml
@model OutcomeSurveyInputModel
@{
    ViewData["Title"] = "Create Outcome Survey";
    var Programs = (List<Program>)ViewBag.Programs;
    var Surveys = (List<Survey>)ViewBag.Surveys;
}

<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Survey" asp-action="Index">Surveys</a></li>
        <li class="breadcrumb-item"><a asp-action="Index">Outcome Surveys</a></li>
        <li class="breadcrumb-item active">New Outcome Survey</li>
    </ol>
</nav>

<form method="post">
    <div class="form-floating mb-3">
        <select asp-for="SurveyId" class="form-select">
            @foreach (var survey in Surveys)
            {
                <option value="@survey.Id">@survey.Name</option>
            }
        </select>
        <label asp-for="SurveyId"></label>
    </div>
    <div class="form-floating mb-3">
        <select asp-for="ProgramId" class="form-select">
            @foreach (var program in Programs)
            {
                <option value="@program.Id">@program.Name</option>
            }
        </select>
        <label asp-for="ProgramId"></label>
    </div>
    <div class="form-floating mb-3">
        <select asp-for="ConstituencyType" class="form-select" asp-items="Html.GetEnumSelectList<ConstituencyType>()"></select>
        <label asp-for="ConstituencyType"></label>
    </div>
    <a class="btn btn-secondary me-2" asp-action="Index">Cancel</a>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

Ascent/Areas/Survey/Views/OutcomeSurvey/Index.cshtml
@model List<OutcomeSurvey>
@{
    ViewData["Title"] = "Outcome Surveys";
}

<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Survey" asp-action="Index">Surveys</a></li>
        <li class="breadcrumb-item active me-auto">Outcome Surveys</li>
        <li>
            <a asp-controller="OutcomeChart" asp-action="Index" class="btn btn-outline-primary btn-sm" title="Outcome Survey Charts">
                <i class="bi bi-bar-chart-line-fill"></i>
            </a>
        </li>
        @if (ViewBag.ShowAdd)
        {
            <li>
                <a asp-action="Add" class="btn btn-outline-primary btn-sm ms-2" title="Add Outcome Survey">
                    <i class="bi bi-plus-lg"></i>
                </a>
            </li>
        }
    </ol>
</nav>

@if (Model.Count > 0)
{
    <table class="table table-striped align-middle">
        <thead>
            <tr>
                <th>Survey</th>
                <th class="d-none d-lg-table-cell">Program</th>
                <th class="d-none d-lg-table-cell">Constituency</th>
                <th>Data Import</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var outcomeSurvey in Model)
            {
                <tr>
                    <td>
                        <a asp-action="View" asp-route-id="@outcomeSurvey.Id">@outcomeSurvey.Survey.Name</a>
                    </td>
                    <td class="d-none d-lg-table-cell">@outcomeSurvey.Program.Name</td>
                    <td class="d-none d-lg-table-cell">@outcomeSurvey.ConstituencyType</td>
                    <td>
                        <a asp-action="ImportData" asp-route-id="@outcomeSurvey.Id" title="Import Data"
                           class="btn btn-outline-primary btn-sm">
                            @if (outcomeSurvey.DataImportTime.HasValue)
                            {
                                <span class="badge text-bg-secondary">@outcomeSurvey.DataImportTime?.ToLocalTime().ToString("d")</span>
                            }
                            <i class="bi bi-box-arrow-down"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Ascent/Areas/Survey/Views/OutcomeSurvey/View.cshtml
@model OutcomeSurvey
@{
    ViewData["Title"] = "View Outcome Survey";
    var Questions = (List<SurveyQuestion>)ViewBag.Questions;
    var questionIdToOutcomeIndex = Model.QuestionIds.Select((id, index) => new { id, index }).ToDictionary(x => x.id, x => x.index + 1);
}
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item d-none d-lg-block"><a asp-controller="Survey" asp-action="Index">Surveys</a></li>
        <li class="breadcrumb-item d-none d-lg-block"><a asp-controller="OutcomeSurvey" asp-action="Index">Outcome Surveys</a></li>
        <li class="breadcrumb-item active me-auto">@Model.Survey.Name</li>
        <li>
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-primary btn-sm" title="Edit Outcome Survey">
                <i class="bi bi-pencil-fill"></i>
            </a>
        </li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-9">
        <div class="form-floating mb-3">
            <span class="form-control">@Model.Program.Name</span>
            <label>Program</label>
        </div>
    </div>
    <div class="col-md-3">
        <div class="form-floating mb-3">
            <span class="form-control">@Model.ConstituencyType.ToString()</span>
            <label>Constituency</label>
        </div>
    </div>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr><th>Outcome</th><th>Question</th></tr>
    </thead>
    <tbody>
        @foreach (var question in Questions)
        {
            <tr>
                <td class="text-center align-middle">
                    @if (questionIdToOutcomeIndex.ContainsKey(question.Id))
                    {
                        <text>@questionIdToOutcomeIndex[question.Id]</text>
                    }
                </td>
                <td>@Html.Raw(question.Description)</td>
            </tr>
        }
    </tbody>
</table>