Ascent/Models/Project.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Ascent.Models;

public class Project
{
    public enum MemberType
    {
        Student = 1,
        Advisor = 2,
        Liaison = 3
    }

    public int Id { get; set; }

    // In the form of xxxx-yyyy, e.g. 2022-2023
    [MaxLength(12)]
    public string AcademicYear { get; set; }

    [Required, MaxLength(255)]
    public string Title { get; set; }

    public string Description { get; set; }

    [MaxLength(255)]
    public string Sponsor { get; set; }

    public List<ProjectMember> Members { get; set; } = new List<ProjectMember>();
    public List<ProjectResource> Resources { get; set; } = new List<ProjectResource>();

    public bool IsDeleted { get; set; }

    [NotMapped]
    public List<ProjectMember> Students => Members.Where(m => m.Type == MemberType.Student).ToList();
    [NotMapped]
    public List<ProjectMember> Advisors => Members.Where(m => m.Type == MemberType.Advisor).ToList();
    [NotMapped]
    public List<ProjectMember> Liaisons => Members.Where(m => m.Type == MemberType.Liaison).ToList();
}

// In some rare cases (hi francisco!), someone can be both an advisor and a liaison.
[PrimaryKey(nameof(ProjectId), nameof(PersonId), nameof(Type))]
public class ProjectMember
{
    public int ProjectId { get; set; }
    public Project Project { get; set; }

    public int PersonId { get; set; }
    public Person Person { get; set; }

    public Project.MemberType Type { get; set; }
}

public class ProjectResource
{
    public int Id { get; set; }

    public int ProjectId { get; set; }
    public Project Project { get; set; }

    [Required, MaxLength(255)]
    public string Name { get; set; }

    [MaxLength(10)]
    public ResourceType Type { get; set; }

    public int? FileId { get; set; }
    public File File { get; set; }

    public string Text { get; set; }

    [MaxLength(2000)]
    public string Url { get; set; }

    public bool IsPrivate { get; set; }
}

Ascent/Areas/Project/Controllers/ProjectController.cs
using System.ComponentModel.DataAnnotations;
using Ascent.Helpers;
using Ascent.Models;
using Ascent.Security;
using Ascent.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ascent.Areas.Project.Controllers
{
    [Area("Project")]
    [Authorize] // The default policy is CanRead; here we only need Authenticated for the operations that check CanManageProject.
    public class ProjectController : Controller
    {
        private readonly PersonService _personService;
        private readonly ProjectService _projectService;

        private readonly IAuthorizationService _authorizationService;

        private readonly AppMapper _mapper;
        private readonly ILogger<ProjectController> _logger;

        public ProjectController(PersonService personService, ProjectService projectService,
            IAuthorizationService authorizationService, AppMapper mapper, ILogger<ProjectController> logger)
        {
            _personService = personService;
            _projectService = projectService;
            _authorizationService = authorizationService;
            _mapper = mapper;
            _logger = logger;
        }

        [AllowAnonymous]
        public IActionResult Index(string year)
        {
            var academicYears = _projectService.GetAcademicYears();
            var academicYear = year != null ? year : academicYears.FirstOrDefault();

            ViewBag.AcademicYears = academicYears;
            ViewBag.AcademicYear = academicYear;

            return View(_projectService.GetProjects(academicYear));
        }

        [AllowAnonymous]
        public IActionResult View(int id)
        {
            var project = _projectService.GetFullProject(id);
            if (project == null) return NotFound();

            return View(project);
        }

        [HttpGet]
        [Authorize(Policy = Constants.Policy.CanWrite)]
        public IActionResult Add()
        {
            var currentYear = DateTime.Now.Year;
            return View(new ProjectInputModel()
            {
                AcademicYear = $"{currentYear}-{currentYear + 1}"
            });
        }

        [HttpPost]
        [Authorize(Policy = Constants.Policy.CanWrite)]
        public IActionResult Add(ProjectInputModel input)
        {
            if (!ModelState.IsValid) return View(input);

            var project = _mapper.Map(input);
            _projectService.AddProject(project);
            _logger.LogInformation("{user} created project {project}", User.GetName(), project.Id);

            return RedirectToAction("Members", new { id = project.Id });
        }

        [HttpGet]
        public async Task<IActionResult> EditAsync(int id)
        {
            var authResult = await _authorizationService.AuthorizeAsync(User, id, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            var project = _projectService.GetProject(id);
            if (project == null) return NotFound();

            ViewBag.Project = project;

            return View(_mapper.Map(project));
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, ProjectInputModel input)
        {
            var authResult = await _authorizationService.AuthorizeAsync(User, id, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            if (!ModelState.IsValid) return View(input);

            var project = _projectService.GetProject(id);
            if (project == null) return NotFound();

            _mapper.Map(input, project);
            _projectService.SaveChanges();
            _logger.LogInformation("{user} edited project {project}", User.GetName(), id);

            return RedirectToAction("View", new { id });
        }

        [Authorize(Policy = Constants.Policy.CanWrite)]
        public IActionResult Delete(int id)
        {
            var project = _projectService.GetProject(id);
            if (project == null) return NotFound();

            project.IsDeleted = true;
            _projectService.SaveChanges();
            _logger.LogInformation("{user} deleted project {project}", User.GetName(), id);

            return RedirectToAction("Index", new { year = project.AcademicYear });
        }

        [AllowAnonymous]
        public IActionResult Search(string searchText, int? sectionId)
        {
            return View(_projectService.SearchProjects(searchText));
        }

        [AllowAnonymous]
        public IActionResult ByMember(int memberId, string memberType)
        {
            var member = _personService.GetPerson(memberId);
            if (member == null) return NotFound();

            var ok = Enum.TryParse(memberType, out Models.Project.MemberType type);
            if (!ok) return BadRequest();

            ViewBag.Member = member;
            ViewBag.MemberType = type;

            return View(_projectService.GetProjectsByMember(memberId, type));
        }

        [Authorize(Policy = Constants.Policy.CanWrite)]
        public IActionResult Members(int id)
        {
            var project = _projectService.GetProjectWithMembers(id);
            if (project == null) return NotFound();

            return View(project);
        }

        [Authorize(Policy = Constants.Policy.CanWrite)]
        public IActionResult AddMember(int id, int personId, string memberType)
        {
            _projectService.AddProjectMember(id, personId, memberType);
            _logger.LogInformation("{user} added member {member} to project {project}", User.GetName(), personId, id);

            return RedirectToAction("Members", new { id });
        }

        [Authorize(Policy = Constants.Policy.CanWrite)]
        public IActionResult RemoveMember(int id, int personId, string memberType)
        {
            _projectService.RemoveProjectMember(id, personId, memberType);
            _logger.LogInformation("{user} removed member {member} from project {project}", User.GetName(), personId, id);

            return RedirectToAction("Members", new { id });
        }
    }
}

namespace Ascent.Models
{
    public class ProjectInputModel
    {
        // In the form of xxxx-yyyy, e.g. 2022-2023
        [MaxLength(12), Display(Name = "Academic Year")]
        public string AcademicYear { get; set; }

        [Required, MaxLength(255)]
        public string Title { get; set; }

        public string Description { get; set; }

        [MaxLength(255)]
        public string Sponsor { get; set; }
    }
}

Ascent/Areas/Project/Controllers/ResourceController.cs
using System.ComponentModel.DataAnnotations;
using Ascent.Helpers;
using Ascent.Models;
using Ascent.Security;
using Ascent.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ascent.Areas.Project.Controllers
{
    [Area("Project")]
    [Authorize] // The default policy is CanRead; here we only need Authenticated for the operations that check CanManageProject.
    public class ResourceController : Controller
    {
        private readonly FileService _fileService;
        private readonly ProjectService _projectService;

        private readonly IAuthorizationService _authorizationService;

        private readonly AppMapper _mapper;
        private readonly ILogger<ResourceController> _logger;

        public ResourceController(FileService fileService, ProjectService projectService,
            IAuthorizationService authorizationService, AppMapper mapper, ILogger<ResourceController> logger)
        {
            _fileService = fileService;
            _projectService = projectService;
            _authorizationService = authorizationService;
            _mapper = mapper;
            _logger = logger;
        }

        public async Task<IActionResult> IndexAsync(int projectId)
        {
            var authResult = await _authorizationService.AuthorizeAsync(User, projectId, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            var project = _projectService.GetProjectWithResources(projectId);
            if (project == null) return NotFound();

            return View(project);
        }

        [HttpGet]
        public async Task<IActionResult> AddAsync(int projectId)
        {
            var authResult = await _authorizationService.AuthorizeAsync(User, projectId, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            var project = _projectService.GetProject(projectId);
            if (project == null) return NotFound();

            ViewBag.Project = project;

            return View(new ProjectResourceInputModel()
            {
                ProjectId = projectId
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddAsync(ProjectResourceInputModel input, IFormFile uploadedFile)
        {
            var authResult = await _authorizationService.AuthorizeAsync(User, input.ProjectId, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            var resource = _mapper.Map(input);
            if (resource.Type == ResourceType.File && uploadedFile != null)
            {
                var file = await _fileService.UploadFileAsync(null, uploadedFile, false);
                file.IsPublic = !resource.IsPrivate;
                resource.FileId = file.Id;
            }

            _projectService.AddProjectResource(resource);
            _logger.LogInformation("{user} added resource {resource} to project {project}", User.GetName(),
                resource.Id, resource.ProjectId);

            return RedirectToAction("Index", new { projectId = resource.ProjectId });
        }

        [HttpGet]
        public async Task<IActionResult> EditAsync(int id)
        {
            var resource = _projectService.GetProjectResource(id);
            if (resource == null) return NotFound();

            var authResult = await _authorizationService.AuthorizeAsync(User, resource.ProjectId, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            ViewBag.Resource = resource;

            return View(_mapper.Map(resource));
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var resource = _projectService.GetProjectResource(id);
            if (resource == null) return NotFound();

            var authResult = await _authorizationService.AuthorizeAsync(User, resource.ProjectId, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            _projectService.RemoveProjectResource(resource);
            _logger.LogInformation("{user} removed resource {resource} from project {project}", User.GetName(),
                resource.Id, resource.ProjectId);

            return RedirectToAction("Index", new { projectId = resource.ProjectId });
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, ProjectResourceInputModel input, IFormFile uploadedFile)
        {
            var resource = _projectService.GetProjectResource(id);
            if (resource == null) return NotFound();

            var authResult = await _authorizationService.AuthorizeAsync(User, input.ProjectId, Constants.Policy.CanManageProject);
            if (!authResult.Succeeded)
                return Forbid();

            _mapper.Map(input, resource);
            if (resource.Type == ResourceType.File && uploadedFile != null)
            {
                var file = await _fileService.UploadFileAsync(null, uploadedFile, false);
                file.IsPublic = !resource.IsPrivate;
                resource.FileId = file.Id;
            }

            _projectService.SaveChanges();
            _logger.LogInformation("{user} edited resource {resource} of project {project}", User.GetName(),
                resource.Id, resource.ProjectId);

            return RedirectToAction("Index", new { projectId = resource.ProjectId });
        }

        [AllowAnonymous]
        public async Task<IActionResult> GetAsync(int id, bool inline = false)
        {
            var resource = _projectService.GetProjectResource(id);
            if (resource == null) return NotFound();

            if (resource.IsPrivate &&
                !(await _authorizationService.AuthorizeAsync(User, resource.ProjectId, Constants.Policy.CanManageProject)).Succeeded)
                return Forbid();

            switch (resource.Type)
            {
                case ResourceType.Url:
                    return Redirect(resource.Url);
                case ResourceType.File:
                    return await DownloadFileAsync((int)resource.FileId, inline);
                default:
                    return BadRequest();
            }
        }

        private async Task<IActionResult> DownloadFileAsync(int id, bool inline = false)
        {
            var file = _fileService.GetFile(id);
            if (file == null) return NotFound();
            if (file.IsFolder) return BadRequest();

            return Redirect(await _fileService.GetDownloadUrlAsync(file, inline));
        }
    }
}

namespace Ascent.Models
{
    public class ProjectResourceInputModel
    {
        public int ProjectId { get; set; }

        [Required, MaxLength(255)]
        public string Name { get; set; }

        public ResourceType Type { get; set; }

        public string Text { get; set; }

        [MaxLength(2000)]
        public string Url { get; set; }

        [Display(Name = "Private")]
        public bool IsPrivate { get; set; }
    }
}

Ascent/Areas/Project/Views/Project/Add.cshtml
@model ProjectInputModel
@{
    ViewData["Title"] = "New Project";
}
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index">Projects</a></li>
        <li class="breadcrumb-item active">New Project</li>
    </ol>
</nav>

<form method="post">
    <div class="row">
        <div class="col-md-3 col-lg-2">
            <div class="form-floating mb-3">
                <input asp-for="AcademicYear" class="form-control" required>
                <label asp-for="AcademicYear"></label>
            </div>
        </div>
        <div class="col-md-9 col-lg-10">
            <div class="form-floating mb-3">
                <input asp-for="Sponsor" class="form-control" placeholder="Sponsor">
                <label asp-for="Sponsor"></label>
            </div>
        </div>
        <div class="col-12">
            <div class="form-floating mb-3">
                <input asp-for="Title" class="form-control" placeholder="Title" required>
                <label asp-for="Title"></label>
            </div>
        </div>
        <div class="col-12">
            <div class="form-floating mb-3">
                <textarea asp-for="Description" class="form-control"></textarea>
            </div>
        </div>
        <div class="col-12">
            <a class="btn btn-secondary me-2" asp-action="Index">Cancel</a>
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

@section StyleSheets {
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs5.min.css" />
}
@section Scripts {
    <script src="~/lib/summernote/summernote-bs5.min.js"></script>
    <script src="~/js/summernote-options.js"></script>
    <script>
        $(function () {
            $("#Description").summernote(summernoteOptions.minimal(350));
        });
    </script>
}

Ascent/Areas/Project/Views/Project/ByMember.cshtml
@model List<Project>
@{
    ViewData["Title"] = "Projects by Member";
}
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index">Projects</a></li>
        <li class="breadcrumb-item active">@ViewBag.Member.FullName (@ViewBag.MemberType.ToString())</li>
    </ol>
</nav>

@if (Model.Count > 0)
{
    <table class="table border-top">
        <thead>
            <tr><th>Year</th><th>Title</th><th>Spronsor</th></tr>
        </thead>
        <tbody>
            @foreach (var project in Model)
            {
                <tr>
                    <td>@project.AcademicYear</td>
                    <td><a asp-action="View" asp-route-id="@project.Id">@project.Title</a></td>
                    <td><a asp-action="Search" asp-route-searchText="@project.Sponsor">@project.Sponsor</a></td>
                </tr>
            }
        </tbody>
    </table>
}

Ascent/Areas/Project/Views/Project/Edit.cshtml
@inject IAuthorizationService AuthorizationService
@model ProjectInputModel
@{
    ViewData["Title"] = "Edit Project";
}
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index" asp-route-year="@Model.AcademicYear">Projects</a></li>
        <li class="breadcrumb-item"><a asp-action="View" asp-route-id="@ViewBag.Project.Id">@Model.Title</a></li>
        <li class="breadcrumb-item active me-auto">Edit</li>
        @if ((await AuthorizationService.AuthorizeAsync(User, Constants.Policy.CanWrite)).Succeeded)
        {
            <li>
                <button id="delete" class="btn btn-outline-danger btn-sm" title="Delete Project">
                    <i class="bi bi-trash-fill"></i>
                </button>
            </li>
        }
    </ol>
</nav>

<form method="post">
    <div class="row">
        <div class="col-md-3 col-lg-2">
            <div class="form-floating mb-3">
                <input asp-for="AcademicYear" class="form-control" required>
                <label asp-for="AcademicYear"></label>
            </div>
        </div>
        <div class="col-md-9 col-lg-10">
            <div class="form-floating mb-3">
                <input asp-for="Sponsor" class="form-control" placeholder="Sponsor">
                <label asp-for="Sponsor"></label>
            </div>
        </div>
        <div class="col-12">
            <div class="form-floating mb-3">
                <input asp-for="Title" class="form-control" placeholder="Title" required>
                <label asp-for="Title"></label>
            </div>
        </div>
        <div class="col-12">
            <div class="form-floating mb-3">
                <textarea asp-for="Description" class="form-control" rows="20"></textarea>
            </div>
        </div>
        <div class="col-12 d-flex">
            <a class="btn btn-secondary me-2" asp-action="View" asp-route-id="@ViewBag.Project.Id">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
            @if ((await AuthorizationService.AuthorizeAsync(User, Constants.Policy.CanWrite)).Succeeded)
            {
                <a asp-action="Members" asp-route-id="@ViewBag.Project.Id" class="btn btn-primary ms-auto">Edit Members</a>
            }
        </div>
    </div>
</form>

@section StyleSheets {
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs5.min.css" />
}
@section Scripts {
    <script src="~/lib/summernote/summernote-bs5.min.js"></script>
    <script src="~/js/summernote-options.js"></script>
    <script src="~/lib/prettier/standalone.js"></script>
    <script src="~/lib/prettier/plugins/html.js"></script>
    <script>
        $(function () {
            $("#Description").summernote(summernoteOptions.full("#Description"));
            $("#delete").click(function () {
                if (confirm("Do you want to delete this project?"))
                    window.location.href = "../delete/" + @ViewBag.Project.Id;
            });
        });
    </script>
}

Ascent/Areas/Project/Views/Project/Index.cshtml
@inject IAuthorizationService AuthorizationService
@model List<Project>
@{
    ViewData["Title"] = "Projects";
}
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item active me-auto">Projects</li>
        @if ((await AuthorizationService.AuthorizeAsync(User, Constants.Policy.CanWrite)).Succeeded)
        {
            <li>
                <a asp-action="Add" class="btn btn-outline-primary btn-sm" title="Add Project">
                    <i class="bi bi-plus-lg"></i>
                </a>
            </li>
        }
    </ol>
</nav>

<div class="d-inline-flex mb-2">
    <form id="yearForm" method="get" class="d-inline-flex">
        <select name="year" class="form-select">
            @foreach (var year in ViewBag.AcademicYears)
            {
                if (year == ViewBag.AcademicYear)
                {
                    <option selected>@year</option>
                }
                else
                {
                    <option>@year</option>
                }
            }
        </select>
    </form>
    <form asp-action="Search" method="get" class="d-inline-flex ms-3">
        <input id="search" name="searchText" class="form-control me-2" required>
        <button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button>
    </form>
</div>

<div class="row row-cols-1 row-cols-lg-2 g-4">
    @foreach (var project in Model)
    {
        <div class="col">
            <div class="card h-100">
                @if (!string.IsNullOrEmpty(project.Sponsor))
                {
                    <div class="card-header">
                        Sponsored by <a asp-action="Search" asp-route-searchText="@project.Sponsor">@project.Sponsor</a>
                    </div>
                }
                <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title">@project.Title</h5>
                    <p class="card-text">
                        @for (var i = 0; i < project.Students.Count; ++i)
                        {
                            <text>@project.Students[i].Person.FullName</text>
                            if (i < project.Students.Count - 1)
                            {
                                <text>, </text>
                            }
                        }
                    </p>
                    <div>
                        <a asp-action="View" asp-route-id="@project.Id" class="btn btn-primary">View</a>
                    </div>
                </div>
                @if (project.Advisors.Count > 0)
                {
                    <div class="card-footer text-end">
                        Advised by
                        @for (int i = 0; i < project.Advisors.Count; ++i)
                        {
                            <a asp-action="ByMember" asp-route-memberId="@project.Advisors[i].PersonId"
                               asp-route-memberType="Advisor">@project.Advisors[i].Person.FullName</a>
                            if (i < project.Advisors.Count - 1)
                            {
                                <text>, </text>
                            }
                        }
                    </div>
                }
            </div>
        </div>
    }
</div>

@section Scripts {
    <script>
        $(function () {
            $("select").change(function () {
                $("#yearForm").submit();
            });
        })
    </script>
}

Ascent/Areas/Project/Views/Project/Search.cshtml
@model List<Project>
@{
    ViewData["Title"] = "Search Projects";
    var searchText = Context.Request.Query["searchText"];
}
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-action="Index">Projects</a></li>
        <li class="breadcrumb-item active">Search</li>
    </ol>
</nav>

<form method="get" class="d-inline-flex mb-3">
    <input id="search" name="searchText" class="form-control me-2" value="@searchText" required>
    <button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button>
</form>

@if (Model.Count > 0)
{
    <table class="table border-top">
        <thead>
            <tr><th>Year</th><th>Title</th><th>Spronsor</th></tr>
        </thead>
        <tbody>
            @foreach (var project in Model)
            {
                <tr>
                    <td><a asp-action="Index" asp-route-year="@project.AcademicYear">@project.AcademicYear</a></td>
                    <td><a asp-action="View" asp-route-id="@project.Id">@project.Title</a></td>
                    <td><a asp-action="Search" asp-route-searchText="@project.Sponsor">@project.Sponsor</a></td>
                </tr>
            }
        </tbody>
    </table>
}

Ascent/Areas/Project/Views/Project/View.cshtml
@inject IAuthorizationService AuthorizationService
@model Project
@{
    ViewData["Title"] = "Project";
}
<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item d-none d-lg-block">
            <a asp-controller="Project" asp-action="Index" asp-route-year="@Model.AcademicYear">Projects</a>
        </li>
        <li class="breadcrumb-item d-none d-lg-block active me-auto">@Model.Title</li>
        @if ((await AuthorizationService.AuthorizeAsync(User, Model.Id, Constants.Policy.CanManageProject)).Succeeded)
        {
            <li class="d-none d-lg-block">
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-primary btn-sm" title="Edit Project">
                    <i class="bi bi-pencil-fill"></i>
                </a>
            </li>
        }
    </ol>
</nav>

<h5 class="text-center">@Model.Title</h5>

<div class="row p-3">@Html.Raw(Model.Description)</div>

<div class="row g-2">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">Student Team</div>
            <ul class="list-group list-group-flush">
                @foreach (var student in Model.Students)
                {
                    <li class="list-group-item">@student.Person.FullName</li>
                }
            </ul>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card mb-2">
            <div class="card-header">Project Sponsor</div>
            <div class="card-body"><a asp-action="Search" asp-route-searchText="@Model.Sponsor">@Model.Sponsor</a></div>
        </div>
        <div class="card mb-2">
            <div class="card-header">Project Liaisons</div>
            <ul class="list-group list-group-flush">
                @foreach (var liaison in Model.Liaisons)
                {
                    <li class="list-group-item">
                        <a asp-action="ByMember" asp-route-memberId="@liaison.PersonId" asp-route-memberType="Liaison">@liaison.Person.FullName</a>
                    </li>
                }
            </ul>
        </div>

        <div class="card">
            <div class="card-header d-flex align-items-center">Faculty Advisors</div>
            <ul class="list-group list-group-flush">
                @foreach (var advisor in Model.Advisors)
                {
                    <li class="list-group-item">
                        <a asp-action="ByMember" asp-route-memberId="@advisor.PersonId" asp-route-memberType="Advisor">@advisor.Person.FullName</a>
                    </li>
                }
            </ul>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header d-flex align-items-center">
                <span>Resources</span>
                @if ((await AuthorizationService.AuthorizeAsync(User, Model.Id, Constants.Policy.CanManageProject)).Succeeded)
                {
                    <a asp-controller="Resource" asp-action="Index" asp-route-projectId="@Model.Id"
                       class="btn btn-outline-primary btn-sm ms-auto" title="Edit Resources">
                        <i class="bi bi-pencil-fill"></i>
                    </a>
                }
            </div>
            <ul class="list-group list-group-flush">
                @foreach (var resource in Model.Resources)
                {
                    <li class="list-group-item d-flex">
                        @if (resource.IsPrivate)
                        {
                            <i class="bi bi-lock-fill me-2"></i>
                        }
                        @switch (resource.Type)
                        {
                            case ResourceType.Text:
                                <text>@resource.Name</text>
                                break;
                            case ResourceType.Url:
                                <a asp-controller="Resource" asp-action="Get" asp-route-id="@resource.Id">@resource.Name</a>
                                break;
                            case ResourceType.File:
                                <a asp-controller="Resource" asp-action="Get" asp-route-id="@resource.Id" asp-route-inline="true"
                                   class="me-auto" style="z-index: 3">@resource.Name</a>
                                <a asp-controller="Resource" asp-action="Get" asp-route-id="@resource.Id"
                                   class="btn btn-outline-primary btn-sm stretched-link">
                                    <i class="bi bi-download"></i>
                                </a>
                                break;
                        }
                    </li>
                }
            </ul>
        </div>
    </div>
</div>